[project]
name = "analise-evasao-inep-ibge"
version = "0.0.0"
dependencies = [
	"pyyaml",
	"pandas",
	"numpy",
    "matplotlib",
    "geopandas",
    "xlrd",
    "plotly",
]

[tool.setuptools]
package-dir = {"" = "src"}
