saida:
  encoding: "utf-8"
  sep: ";"

municipio:
  codigo: "CO_MUNICIPIO"
  nome: "NO_MUNICIPIO"

estado:
  sigla: "SG_UF"

nacional:
  coluna: "ID_BRASIL"  # Nome para agregação nacional, decidido pelo usuário
