linha_temporal:
  plot:
    figsize: [8, 4]
    mostrar_titulo: true
    grid: true
    max_variaveis_por_plot: 4

  plots:
    - nome: Ingresso Nacional Total
      nivel: nacional
      variaveis:
        - QT_ING_TOTAL

    - nome: evasao_anual_nacional
      nivel: nacional
      variaveis:
        - evasao_anual

    - nome: ingresso_vs_evasao_nacional
      nivel: nacional
      variaveis:
        - TP_REDE_1
        - TP_REDE_2
        - evasao_anual

    - nome: evasao_anual_ba
      nivel: estadual
      territorio:
        ufs: "BA"
      variaveis:
        - evasao_anual

  saida:
    formato: png
    dpi: 150

scatter:
  plot:
    figsize: [6, 6]
    mostrar_titulo: true
    grid: true

  plots:
    - nome: ingresso_vs_populacao_nacional
      nivel: nacional
      eixo_x: QT_MAT_TOTAL
      eixo_y: QT_ING_TOTAL

    - nome: ingresso_vs_evasao_nacional
      nivel: nacional
      eixo_x: QT_ING_TOTAL
      eixo_y: evasao_anual

    - nome: evasao_vs_evasao_nacional
      nivel: nacional
      eixo_x: evasao_anual
      eixo_y: evasao_anual

    - nome: evasao_vs_ingresso_ba
      nivel: estadual
      territorio:
        ufs: "BA"
      eixo_x: evasao_anual
      eixo_y: QT_ING_TOTAL

  saida:
    formato: png
    dpi: 150
