linha_temporal:
  plot:
    figsize: [8, 4]
    mostrar_titulo: true
    grid: true
    max_variaveis_por_plot: 4

  plots:
    - nome: Ingresso Nacional Total
      nivel: nacional
      variaveis:
        - QT_ING_TOTAL

    - nome: Evasão Anual Nacional
      nivel: nacional
      variaveis:
        - evasao_anual

    - nome: Ingresso vs Tipos de Redes
      nivel: nacional
      variaveis:
        - TP_REDE_1
        - TP_REDE_2
        - evasao_anual

    - nome: Evasão na Bahia
      nivel: estadual
      territorio:
        ufs: "BA"
      variaveis:
        - evasao_anual

  saida:
    formato: png
    dpi: 150

scatter:
  plot:
    figsize: [6, 6]
    mostrar_titulo: true
    grid: true

  plots:
    - nome: Matriculados vs Ingressantes
      nivel: nacional
      eixo_x: POP_TOTAL
      eixo_y: QT_ING_TOTAL

    - nome: Evasão vs Rede Publica
      nivel: nacional
      eixo_x: TP_REDE_1
      eixo_y: evasao_anual

    - nome: Evasão vs Rede Privada
      nivel: nacional
      eixo_x: TP_REDE_2
      eixo_y: evasao_anual

    - nome: Evasão vs Rede Publica na Bahia
      nivel: estadual
      territorio:
        ufs: "BA"
      eixo_x: evasao_anual
      eixo_y: TP_REDE_1

  saida:
    formato: png
    dpi: 150
