linha_temporal:
  plot:
    figsize:
      - 8.0
      - 4.0
    mostrar_titulo: true
    grid: true
    max_variaveis_por_plot: 4

  plots:
    - nome: Ingressantes x Concluintes Nacional
      nivel: nacional
      variaveis:
        - QT_ING_TOTAL
        - QT_CONC_TOTAL
    - nome: Evasão Anual Nacional
      nivel: nacional
      variaveis:
        - evasao_anual
        - evasao_anual_financiados
    - nome: Percentuais de Matriculados por Tipo de Rede
      nivel: nacional
      variaveis:
        - TP_REDE_Publica
        - TP_REDE_Privada
    - nome: Percentuais de Matriculados por Tipo de Modalidade de Ensino
      nivel: nacional
      variaveis:
        - TP_MODALIDADE_ENSINO_Presencial
        - TP_MODALIDADE_ENSINO_EaD
    - nome: Evasão Anual na Bahia
      nivel: estadual
      territorio:
        ufs: "BA"
      variaveis:
        - evasao_anual
        - evasao_anual_financiados
  saida:
    formato: png
    dpi: 150

scatter:
  plot:
    figsize:
      - 6.0
      - 6.0
    mostrar_titulo: true
    grid: true

  plots:
    - nome: Matriculados vs Ingressantes
      nivel: nacional
      eixo_x: POP_TOTAL
      eixo_y: QT_ING_TOTAL

    - nome: Evasão vs Rede Publica
      nivel: nacional
      eixo_x: TP_REDE_Publica
      eixo_y: evasao_anual

    - nome: Evasão vs Rede Privada
      nivel: nacional
      eixo_x: TP_REDE_Privada
      eixo_y: evasao_anual

    - nome: Evasão vs Rede Publica na Bahia
      nivel: estadual
      territorio:
        ufs: "BA"
      eixo_x: evasao_anual
      eixo_y: TP_REDE_Publica

  saida:
    formato: png
    dpi: 150
