# Colunas base comuns a todos os datasets que representam municípios/estados no Brasil

municipio:
  codigo: "CO_MUNICIPIO"
  nome:   "NO_MUNICIPIO"

estado:
  sigla: "SG_UF"

nacional:
  coluna: "BRASIL"  # Nome para agregação nacional, decidido pelo usuário