arquivo_final_municipios: "ibge_final_municipios.csv"
arquivo_final_estados: "ibge_final_estados.csv"
arquivo_final_nacional: "ibge_final_nacional.csv"

formato_padrao: "CONTAGEM"

colunas_peso:
  populacao: POP_TOTAL
  unidades: UNIDADES_DOMESTICAS_TOTAL
  domicilios: DOMICILIOS_TOTAL


tabelas:
  tab1:
    descricao_tabela: "População total do município, com distribuição urbano/rural
      e por sexo."
    sheets:
      - descricao_sheet: "Conjunto completo da tabela, sem subdivisões."
        arquivo: "tab1_populacao_total.csv"

        colunas:
          - POP_TOTAL: CONTAGEM
          - PERC_URBANA:
              formato: PROPORCAO
              coluna_peso: populacao
          - PERC_RURAL: CONTAGEM
          - PERC_HOMEM:
              formato: PROPORCAO
              coluna_peso: populacao
          - PERC_MULHER: CONTAGEM
          - RAZAO_SEXO: CONTAGEM
        remover_colunas_idx:
          - 3
          - 5
          - 6
  tab2:
    descricao_tabela: "População residente por faixas etárias, com detalhamento total,
      urbano e rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "Totais gerais de população por faixas etárias."
        arquivo: "tab2_faixas_etarias_total.csv"

        colunas:
          - POP_RESIDENTE_TOTAL: CONTAGEM
          - PERC_0_A_5: CONTAGEM
          - PERC_6_A_14: CONTAGEM
          - PERC_15_A_24: CONTAGEM
          - PERC_25_A_39: CONTAGEM
          - PERC_40_A_59: CONTAGEM
          - PERC_60_OU_MAIS: CONTAGEM
        merges_colunas:
          - destino: IDADE_MEDIA_ESTIMADA
            fontes_idx: [2, 3, 4, 5, 6, 7]
            metodo: MEDIA_PONDERADA
            peso_merge: [2.5, 10, 19.5, 32, 49.5, 70]
            formato: MEDIA
            coluna_peso: "populacao"

        remover_colunas_idx:
          - 1
      - sheet_id: B
        descricao_sheet: "População urbana por faixas etárias."
        arquivo: "tab2_faixas_etarias_urbana.csv"

        colunas:
          - POP_RESIDENTE_URBANA: CONTAGEM
          - PERC_0_A_5_URBANA: CONTAGEM
          - PERC_6_A_14_URBANA: CONTAGEM
          - PERC_15_A_24_URBANA: CONTAGEM
          - PERC_25_A_39_URBANA: CONTAGEM
          - PERC_40_A_59_URBANA: CONTAGEM
          - PERC_60_OU_MAIS_URBANA: CONTAGEM
        merges_colunas:
          - destino: IDADE_MEDIA_ESTIMADA_URBANA
            fontes_idx: [2, 3, 4, 5, 6, 7]
            metodo: MEDIA_PONDERADA
            peso_merge: [2.5, 10, 19.5, 32, 49.5, 70]
            formato: PROPORCAO
            coluna_peso: "populacao"

      - sheet_id: C
        descricao_sheet: "População rural por faixas etárias."
        arquivo: "tab2_faixas_etarias_rural.csv"

        colunas:
          - POP_RESIDENTE_RURAL: CONTAGEM
          - PERC_0_A_5_RURAL: CONTAGEM
          - PERC_6_A_14_RURAL: CONTAGEM
          - PERC_15_A_24_RURAL: CONTAGEM
          - PERC_25_A_39_RURAL: CONTAGEM
          - PERC_40_A_59_RURAL: CONTAGEM
          - PERC_60_OU_MAIS_RURAL: CONTAGEM
        merges_colunas:
          - destino: IDADE_MEDIA_ESTIMADA_RURAL
            fontes_idx: [2, 3, 4, 5, 6, 7]
            metodo: MEDIA_PONDERADA
            peso_merge: [2.5, 10, 19.5, 32, 49.5, 70]
            formato: MEDIA
            coluna_peso: "populacao"

  tab4:
    descricao_tabela: "Unidades domésticas segundo o sexo do responsável, incluindo
      indicadores de responsabilidade única ou compartilhada."
    sheets:
      - descricao_sheet: "Tabela única contendo totais e distribuição por sexo do
          responsável."
        arquivo: "tab4_unidades_domesticas_por_sexo.csv"

        colunas:
          - UNIDADES_DOMESTICAS_TOTAL: CONTAGEM
          - PERC_UNICO_RESP:
              formato: PROPORCAO
              coluna_peso: unidades
          - PERC_MAIS_DE_1_RESP: CONTAGEM
          - UNIDADES_DOMESTICAS_HOMEM: CONTAGEM
          - PERC_UNICO_RESP_HOMEM: CONTAGEM
          - PERC_MAIS_DE_1_RESP_HOMEM: CONTAGEM
          - UNIDADES_DOMESTICAS_MULHER: CONTAGEM
          - PERC_UNICO_RESP_MULHER: CONTAGEM
          - PERC_MAIS_DE_1_RESP_MULHER: CONTAGEM
        remover_colunas_idx:
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
  tab7:
    descricao_tabela: "Condições de saneamento dos domicílios, separadas por totais,
      área urbana e área rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "Situação de saneamento considerando todos os domicílios
          do município."
        arquivo: "tab7_saneamento_total.csv"

        colunas:
          - DOMICILIOS_TOTAL: CONTAGEM
          - PERC_SANEAMENTO_ADEQUADO: CONTAGEM
          - PERC_SANEAMENTO_SEMI_ADEQUADO: CONTAGEM
          - PERC_SANEAMENTO_INADEQUADO:
              formato: PROPORCAO
              coluna_peso: domicilios
        remover_colunas_idx:
          - 2
          - 3
      - sheet_id: B
        descricao_sheet: "Situação de saneamento dos domicílios em áreas urbanas."
        arquivo: "tab7_saneamento_urbano.csv"

        colunas:
          - DOMICILIOS_URBANOS: CONTAGEM
          - PERC_SANEAMENTO_ADEQUADO_URBANO: CONTAGEM
          - PERC_SANEAMENTO_SEMI_ADEQUADO_URBANO: CONTAGEM
          - PERC_SANEAMENTO_INADEQUADO_URBANO: CONTAGEM
      - sheet_id: C
        descricao_sheet: "Situação de saneamento dos domicílios em áreas rurais."
        arquivo: "tab7_saneamento_rural.csv"

        colunas:
          - DOMICILIOS_RURAIS: CONTAGEM
          - PERC_SANEAMENTO_ADEQUADO_RURAL: CONTAGEM
          - PERC_SANEAMENTO_SEMI_ADEQUADO_RURAL: CONTAGEM
          - PERC_SANEAMENTO_INADEQUADO_RURAL: CONTAGEM
  tab8:
    descricao_tabela: "Rendimento domiciliar per capita, com estatísticas de valor
      médio e quartis, segmentado por total, área urbana e rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "Distribuição do rendimento domiciliar per capita para o
          total dos domicílios."
        arquivo: "tab8_rendimento_total.csv"
        colunas:
          - RENDA_MEDIA_PER_CAPITA:
              formato: MEDIA
              coluna_peso: populacao
          - QUARTIL_1_TOTAL: CONTAGEM
          - QUARTIL_2_TOTAL: CONTAGEM
          - QUARTIL_3_TOTAL: CONTAGEM
        remover_colunas_idx:
          - 2
          - 3
          - 4
      - sheet_id: B
        descricao_sheet: "Distribuição do rendimento domiciliar per capita apenas
          para áreas urbanas."
        arquivo: "tab8_rendimento_urbano.csv"
        colunas:
          - RENDA_MEDIA_PER_CAPITA_URBANA: CONTAGEM
          - QUARTIL_1_URBANO: CONTAGEM
          - QUARTIL_2_URBANO: CONTAGEM
          - QUARTIL_3_URBANO: CONTAGEM
      - sheet_id: C
        descricao_sheet: "Distribuição do rendimento domiciliar per capita apenas
          para áreas rurais."
        arquivo: "tab8_rendimento_rural.csv"
        colunas:
          - RENDA_MEDIA_PER_CAPITA_RURAL: CONTAGEM
          - QUARTIL_1_RURAL: CONTAGEM
          - QUARTIL_2_RURAL: CONTAGEM
          - QUARTIL_3_RURAL: CONTAGEM
  tab12:
    descricao_tabela: "População residente por faixas de rendimento, com detalhamento
      total, urbano e rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "População residente total por faixas de rendimento."
        arquivo: "tab12_rendimento_total.csv"

        colunas:
          - POP_RESIDENTE_RENDAS_TOTAL: CONTAGEM
          - PERC_ATE_70_REAIS: CONTAGEM
          - PERC_ATE_QUARTO_SM: CONTAGEM
          - PERC_ATE_MEIO_SM:
              formato: PROPORCAO
              coluna_peso: populacao
          - PERC_ATE_60_PERC_MEDIANA: CONTAGEM
        remover_colunas_idx:
          - 1
          - 2
          - 3
          - 5
      - sheet_id: B
        descricao_sheet: "População residente urbana por faixas de rendimento."
        arquivo: "tab12_rendimento_urbano.csv"

        colunas:
          - POP_RESIDENTE_RENDAS_URBANA: CONTAGEM
          - PERC_ATE_70_REAIS_URBANA: CONTAGEM
          - PERC_ATE_QUARTO_SM_URBANA: CONTAGEM
          - PERC_ATE_MEIO_SM_URBANA: CONTAGEM
          - PERC_ATE_60_PERC_MEDIANA_URBANA: CONTAGEM
      - sheet_id: C
        descricao_sheet: "População residente rural por faixas de rendimento."
        arquivo: "tab12_rendimento_rural.csv"

        colunas:
          - POP_RESIDENTE_RENDAS_RURAL: CONTAGEM
          - PERC_ATE_70_REAIS_RURAL: CONTAGEM
          - PERC_ATE_QUARTO_SM_RURAL: CONTAGEM
          - PERC_ATE_MEIO_SM_RURAL: CONTAGEM
          - PERC_ATE_60_PERC_MEDIANA_RURAL: CONTAGEM
  tab16:
    descricao_tabela: "Indicadores de vulnerabilidade de crianças de 0 a 5 anos, considerando
      alfabetização do responsável e condições de saneamento."
    sheets:
      - descricao_sheet: "Tabela única contendo indicadores de vulnerabilidade em
          2000 e 2010."
        arquivo: "tab16_vulnerabilidade_0a5.csv"

        colunas:
          - PERC_RESPONSAVEL_ANALFABETO_2000: CONTAGEM
          - PERC_RESPONSAVEL_ANALFABETO_2010: CONTAGEM
          - PERC_SANEAMENTO_INADEQUADO_2000: CONTAGEM
          - PERC_SANEAMENTO_INADEQUADO_2010: CONTAGEM
          - PERC_AMBOS_ANALFABETO_E_INADEQUADO_2000: CONTAGEM
          - PERC_AMBOS_ANALFABETO_E_INADEQUADO_2010:
              formato: PROPORCAO
              coluna_peso: domicilios
        remover_colunas_idx:
          - 1
          - 2
          - 3
          - 4
          - 5
