arquivo_final_municipios: "ibge_final_municipios.csv"
arquivo_final_estados: "ibge_final_estados.csv"
arquivo_final_nacional: "ibge_final_nacional.csv"

formato_padrao: "COUNT"

colunas_peso:
  populacao: POP_TOTAL
  residentes: POP_RESIDENTE_TOTAL
  unidades: UNIDADES_DOMESTICAS_TOTAL
  domicilios: DOMICILIOS_TOTAL


tabelas:
  tab1:
    descricao_tabela: "População total do município, com distribuição urbano/rural e por sexo."
    sheets:
      - descricao_sheet: "Conjunto completo da tabela, sem subdivisões."
        arquivo: "tab1_populacao_total.csv"

        colunas:
          - POP_TOTAL: COUNT         # idx 1
          - PERC_URBANA:             # idx 2
              formato: RATIO
              coluna_peso: populacao
          - PERC_RURAL              # idx 3
          - PERC_HOMEM:             # idx 4
              formato: RATIO
              coluna_peso: populacao
          - PERC_MULHER             # idx 5
          - RAZAO_SEXO              # idx 6

        remover_colunas_idx:
          - 3
          - 5
          - 6


  tab2:
    descricao_tabela: "População residente por faixas etárias, com detalhamento total, urbano e rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "Totais gerais de população por faixas etárias."
        arquivo: "tab2_faixas_etarias_total.csv"

        colunas:
          - POP_RESIDENTE_TOTAL: COUNT    # idx 1
          - PERC_0_A_5                   # idx 2
          - PERC_6_A_14                  # idx 3
          - PERC_15_A_24                 # idx 4
          - PERC_25_A_39                 # idx 5
          - PERC_40_A_59                 # idx 6
          - PERC_60_OU_MAIS              # idx 7

        merges_colunas:
          - destino: IDADE_MEDIA_RESIDENTE_ESTIMADA
            fontes_idx: [2, 3, 4, 5, 6, 7]
            metodo: MEDIA_PONDERADA
            peso_merge: [2.5, 10, 19.5, 32, 49.5, 70]
            formato: MEDIA
            coluna_peso: "residentes"


      - sheet_id: B
        descricao_sheet: "População urbana por faixas etárias."
        arquivo: "tab2_faixas_etarias_urbana.csv"

        colunas:
          - POP_RESIDENTE_URBANA
          - PERC_0_A_5_URBANA
          - PERC_6_A_14_URBANA
          - PERC_15_A_24_URBANA
          - PERC_25_A_39_URBANA
          - PERC_40_A_59_URBANA
          - PERC_60_OU_MAIS_URBANA

        merges_colunas:
          - destino: IDADE_MEDIA_RESIDENTE_ESTIMADA_URBANA
            fontes_idx: [2, 3, 4, 5, 6, 7]
            metodo: MEDIA_PONDERADA
            peso_merge: [2.5, 10, 19.5, 32, 49.5, 70]
            formato: RATIO
            coluna_peso: "residentes"


      - sheet_id: C
        descricao_sheet: "População rural por faixas etárias."
        arquivo: "tab2_faixas_etarias_rural.csv"

        colunas:
          - POP_RESIDENTE_RURAL
          - PERC_0_A_5_RURAL
          - PERC_6_A_14_RURAL
          - PERC_15_A_24_RURAL
          - PERC_25_A_39_RURAL
          - PERC_40_A_59_RURAL
          - PERC_60_OU_MAIS_RURAL

        merges_colunas:
          - destino: IDADE_MEDIA_RESIDENTE_ESTIMADA_RURAL
            fontes_idx: [2, 3, 4, 5, 6, 7]
            metodo: MEDIA_PONDERADA
            peso_merge: [2.5, 10, 19.5, 32, 49.5, 70]
            formato: MEDIA
            coluna_peso: "residentes"

  tab3:
    descricao_tabela: "Distribuição da população com 15 anos ou mais por grandes faixas etárias."
    sheets:
      - sheet_id: A
        descricao_sheet: "Totais gerais de população de 15 anos ou mais subdivididos por faixa etária."
        arquivo: "tab3_populacao_15_mais.csv"

        colunas:
          - PESSOAS_15_MAIS_TOTAL: COUNT  # idx 1
          - PERC_15_MAIS                  # idx 2
          - PESSOAS_15_24_TOTAL: COUNT    # idx 3
          - PERC_15_24                    # idx 4
          - PESSOAS_25_39_TOTAL: COUNT    # idx 5
          - PERC_25_39                    # idx 6
          - PESSOAS_40_59_TOTAL: COUNT    # idx 7
          - PERC_40_59                    # idx 8
          - PESSOAS_60_MAIS_TOTAL: COUNT  # idx 9
          - PERC_60_MAIS                  # idx 10

        merges_colunas:
          - destino: IDADE_MEDIA_ESTIMADA
            fontes_idx: [4, 6, 8, 10]
            metodo: MEDIA_PONDERADA
            peso_merge: [19.5, 32, 49.5, 70]
            formato: MEDIA
            coluna_peso: "populacao"

        remover_colunas_idx:
          - 1
          - 2
          - 3
          - 5
          - 7
          - 9

  tab4:
    descricao_tabela: "Unidades domésticas segundo o sexo do responsável, incluindo indicadores de responsabilidade única ou compartilhada."
    sheets:
      - descricao_sheet: "Tabela única contendo totais e distribuição por sexo do responsável."
        arquivo: "tab4_unidades_domesticas_por_sexo.csv"

        colunas:
          - UNIDADES_DOMESTICAS_TOTAL: COUNT  # idx 1
          - PERC_UNICO_RESP:                  # idx 2
              formato: RATIO
              coluna_peso: unidades
          - PERC_MAIS_DE_1_RESP               # idx 3
          - UNIDADES_DOMESTICAS_HOMEM: COUNT  # idx 4
          - PERC_UNICO_RESP_HOMEM             # idx 5
          - PERC_MAIS_DE_1_RESP_HOMEM         # idx 6
          - UNIDADES_DOMESTICAS_MULHER: COUNT # idx 7
          - PERC_UNICO_RESP_MULHER            # idx 8
          - PERC_MAIS_DE_1_RESP_MULHER        # idx 9

        remover_colunas_idx:
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9

  tab7:
    descricao_tabela: "Condições de saneamento dos domicílios, separadas por totais, área urbana e área rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "Situação de saneamento considerando todos os domicílios do município."
        arquivo: "tab7_saneamento_total.csv"

        colunas:
          - DOMICILIOS_TOTAL: COUNT          # idx 1
          - PERC_SANEAMENTO_ADEQUADO:        # idx 2
              formato: RATIO
              coluna_peso: domicilios
          - PERC_SANEAMENTO_SEMI_ADEQUADO    # idx 3
          - PERC_SANEAMENTO_INADEQUADO       # idx 4

        remover_colunas_idx:
          - 2
          - 3

      - sheet_id: B
        descricao_sheet: "Situação de saneamento dos domicílios em áreas urbanas."
        arquivo: "tab7_saneamento_urbano.csv"

        colunas:
          - DOMICILIOS_URBANOS
          - PERC_SANEAMENTO_ADEQUADO_URBANO
          - PERC_SANEAMENTO_SEMI_ADEQUADO_URBANO
          - PERC_SANEAMENTO_INADEQUADO_URBANO

      - sheet_id: C
        descricao_sheet: "Situação de saneamento dos domicílios em áreas rurais."
        arquivo: "tab7_saneamento_rural.csv"

        colunas:
          - DOMICILIOS_RURAIS
          - PERC_SANEAMENTO_ADEQUADO_RURAL
          - PERC_SANEAMENTO_SEMI_ADEQUADO_RURAL
          - PERC_SANEAMENTO_INADEQUADO_RURAL

  tab8:
    descricao_tabela: "Rendimento domiciliar per capita, com estatísticas de valor médio e quartis, segmentado por total, área urbana e rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "Distribuição do rendimento domiciliar per capita para o total dos domicílios."
        arquivo: "tab8_rendimento_total.csv"
        colunas:
          - VALOR_MEDIO_TOTAL:
              formato: MEDIA
              coluna_peso: populacao
          - QUARTIL_1_TOTAL
          - QUARTIL_2_TOTAL
          - QUARTIL_3_TOTAL
        
        remover_colunas_idx:
          - 2
          - 3
          - 4

      - sheet_id: B
        descricao_sheet: "Distribuição do rendimento domiciliar per capita apenas para áreas urbanas."
        arquivo: "tab8_rendimento_urbano.csv"
        colunas:
          - VALOR_MEDIO_URBANO
          - QUARTIL_1_URBANO
          - QUARTIL_2_URBANO
          - QUARTIL_3_URBANO

      - sheet_id: C
        descricao_sheet: "Distribuição do rendimento domiciliar per capita apenas para áreas rurais."
        arquivo: "tab8_rendimento_rural.csv"
        colunas:
          - VALOR_MEDIO_RURAL
          - QUARTIL_1_RURAL
          - QUARTIL_2_RURAL
          - QUARTIL_3_RURAL

  tab12:
    descricao_tabela: "População residente por faixas de rendimento, com detalhamento total, urbano e rural."
    sheets:
      - sheet_id: A
        descricao_sheet: "População residente total por faixas de rendimento."
        arquivo: "tab12_rendimento_total.csv"

        colunas:
          - POP_RESIDENTE_RENDAS_TOTAL     # idx 1
          - PERC_ATE_70_REAIS              # idx 2
          - PERC_ATE_QUARTO_SM             # idx 3
          - PERC_ATE_MEIO_SM:              # idx 4
              formato: RATIO
              coluna_peso: residentes
          - PERC_ATE_60_PERC_MEDIANA       # idx 5

        remover_colunas_idx:
          - 1
          - 2
          - 3
          - 5

      - sheet_id: B
        descricao_sheet: "População residente urbana por faixas de rendimento."
        arquivo: "tab12_rendimento_urbano.csv"

        colunas:
          - POP_RESIDENTE_RENDAS_URBANA
          - PERC_ATE_70_REAIS_URBANA
          - PERC_ATE_QUARTO_SM_URBANA
          - PERC_ATE_MEIO_SM_URBANA
          - PERC_ATE_60_PERC_MEDIANA_URBANA

      - sheet_id: C
        descricao_sheet: "População residente rural por faixas de rendimento."
        arquivo: "tab12_rendimento_rural.csv"

        colunas:
          - POP_RESIDENTE_RENDAS_RURAL
          - PERC_ATE_70_REAIS_RURAL
          - PERC_ATE_QUARTO_SM_RURAL
          - PERC_ATE_MEIO_SM_RURAL
          - PERC_ATE_60_PERC_MEDIANA_RURAL

  tab16:
    descricao_tabela: "Indicadores de vulnerabilidade de crianças de 0 a 5 anos, considerando alfabetização do responsável e condições de saneamento."
    sheets:
      - descricao_sheet: "Tabela única contendo indicadores de vulnerabilidade em 2000 e 2010."
        arquivo: "tab16_vulnerabilidade_0a5.csv"

        colunas:
          - PERC_RESPONSAVEL_ANALFABETO_2010           # idx 1
          - PERC_SANEAMENTO_INADEQUADO_2010            # idx 2
          - PERC_AMBOS_ANALFABETO_E_INADEQUADO_2010:   # idx 3
              formato: RATIO
              coluna_peso: domicilios

        remover_colunas_idx:
          - 1
          - 2