dados:
  formato: long        # wide | long
  separador: ";"

  arquivos:
    municipio: inep_municipios_2020_2022_L.csv
    uf: inep_estados_2020_2022_L.csv
    nacional: inep_nacional_2020_2022_L.csv

  metricas:
    principal:
      coluna_mapa: VALOR_MAPA

      wide:
        coluna_valor: EVASAO_ANUAL

      long:
        coluna_ano: NU_ANO_CENSO
        coluna_valor: EVASAO_ANUAL
        agregacao: mean
        anos: [2020, 2021, 2022]

colunas:
  territoriais:
    municipio:
      malha: CD_MUN
      tabela: CO_MUNICIPIO
      uf: SG_UF

    uf:
      malha: SIGLA_UF
      tabela: SG_UF

plot:
  cmap: OrRd
  legend_shrink: 0.5

municipios:
  figsize: [14, 14]
  legend_label: "Valor médio da métrica"

uf:
  figsize: [14, 14]
  legend_label: "Valor médio estadual"
