dados:
  formato: long        # wide | long
  arquivo: inep_municipios_2020_2022_L.csv
  separador: ";"

  metricas:
    principal:
      coluna_mapa: VALOR_MAPA

      wide:
        coluna_valor: EVASAO_ANUAL

      long:
        coluna_ano: NU_ANO_CENSO
        coluna_valor: EVASAO_ANUAL
        agregacao: mean
        anos: [2020, 2021, 2022]

colunas:
  territoriais:
    municipio:
      malha: CD_MUN
      tabela: CO_MUNICIPIO
      uf: SG_UF

plot:
  cmap: OrRd
  legend_shrink: 0.5

municipios:
  figsize: [14, 14]
  legend_label: "Valor médio da métrica"

uf:
  figsize: [10, 10]
  legend_label: "Valor médio estadual"
